// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Icons;

{ITE} {$R 'IconsF.dfm' Form1:TForm} {DFMFileType} {IconsF.dfm}
{ITE} {$R 'Icons_DRC.res' 'Icons_DRC.rc'} {RCFileType} {Icons_DRC.rc}

{$E ita}

begin
end.